import type { SpriteDoc } from './types';
import { buildSheet, framePad, frameSize, type AnimDef } from './animation';
import { compose, toPng } from './store';
import { createZip, type ZipEntry } from '../export/zip';
import { dataUrlToBytes, downloadBlob, safeFileName } from '../utils/download';

// Export of characters / objects: spritesheet PNG, JSON (any engine) and a ready Godot 4
// folder – copy it into the project, drag the .tscn into a scene, done.

export interface SheetMeta {
  name: string;
  frameWidth: number;
  frameHeight: number;
  columns: number;
  animations: { name: string; row: number; frames: number; fps: number; loop: boolean }[];
}

export type Fps = Record<string, number>;

function sheet(doc: SpriteDoc, anims: AnimDef[], fps: Fps) {
  const { canvas, rows, cols } = buildSheet(doc, anims);
  const meta: SheetMeta = {
    name: doc.name,
    frameWidth: frameSize(doc.size),
    frameHeight: frameSize(doc.size),
    columns: cols,
    animations: rows.map((r) => ({ name: r.anim.id, row: r.row, frames: r.frames, fps: fps[r.anim.id] ?? r.anim.fps, loop: r.anim.loop })),
  };
  return { canvas, meta };
}

const pngBytes = (c: HTMLCanvasElement) => dataUrlToBytes(c.toDataURL('image/png'));

/** lowest opaque row of the still image = feet line */
export function feetRow(doc: SpriteDoc): number {
  const img = compose({ ...doc, layers: doc.layers.filter((l) => l.slot !== 'shadow') });
  for (let y = doc.size - 1; y >= 0; y--) for (let x = 0; x < doc.size; x++) if (img[(y * doc.size + x) * 4 + 3] > 0) return y;
  return doc.size - 1;
}

export function exportSheetPng(doc: SpriteDoc, anims: AnimDef[], fps: Fps, scale = 1) {
  const { canvas } = sheet(doc, anims, fps);
  let c = canvas;
  if (scale > 1) {
    c = document.createElement('canvas');
    c.width = canvas.width * scale;
    c.height = canvas.height * scale;
    const g = c.getContext('2d')!;
    g.imageSmoothingEnabled = false;
    g.drawImage(canvas, 0, 0, c.width, c.height);
  }
  downloadBlob(new Blob([pngBytes(c) as BlobPart], { type: 'image/png' }), `${safeFileName(doc.name)}-sheet${scale > 1 ? `@${scale}x` : ''}.png`);
}

function godotFrames(file: string, meta: SheetMeta): string {
  const subs: string[] = [];
  const anims: string[] = [];
  let id = 0;
  for (const a of meta.animations) {
    const frames: string[] = [];
    for (let i = 0; i < a.frames; i++) {
      const sid = `AtlasTexture_${id++}`;
      subs.push(`[sub_resource type="AtlasTexture" id="${sid}"]\natlas = ExtResource("1_sheet")\nregion = Rect2(${i * meta.frameWidth}, ${a.row * meta.frameHeight}, ${meta.frameWidth}, ${meta.frameHeight})\n`);
      frames.push(`{\n"duration": 1.0,\n"texture": SubResource("${sid}")\n}`);
    }
    anims.push(`{\n"frames": [${frames.join(', ')}],\n"loop": ${a.loop},\n"name": &"${a.name}",\n"speed": ${a.fps.toFixed(1)}\n}`);
  }
  return `[gd_resource type="SpriteFrames" load_steps=${subs.length + 2} format=3]

[ext_resource type="Texture2D" path="${file}" id="1_sheet"]

${subs.join('\n')}
[resource]
animations = [${anims.join(', ')}]
`;
}

const PLAYER_SCRIPT = `extends CharacterBody2D
## Top-down movement, generated by MapForge.
## Arrow keys (ui_left / ui_right / ui_up / ui_down). Plays "walk" while moving, "idle" otherwise.

@export var speed := 90.0
@onready var sprite: AnimatedSprite2D = $AnimatedSprite2D

func _physics_process(_delta: float) -> void:
\tvar dir := Input.get_vector("ui_left", "ui_right", "ui_up", "ui_down")
\tvelocity = dir * speed
\tmove_and_slide()
\tif dir.x != 0.0:
\t\tsprite.flip_h = dir.x < 0.0
\tvar anim := "walk" if dir != Vector2.ZERO else "idle"
\tif sprite.sprite_frames.has_animation(anim) and sprite.animation != anim:
\t\tsprite.play(anim)
`;

function godotScene(doc: SpriteDoc, base: string, meta: SheetMeta, feet: number): string {
  const node = doc.name.replace(/[^\p{L}\p{N}_]/gu, '_') || 'Sprite';
  const character = doc.kind === 'character';
  const first = meta.animations.find((a) => a.name === 'idle')?.name ?? meta.animations[0]?.name ?? 'default';
  // feet of the sprite at the node origin (y-sort / collision work from the feet)
  const F = frameSize(doc.size);
  const offY = -(feet + framePad(doc.size) + 1 - F / 2);
  return `[gd_scene load_steps=${character ? 4 : 3} format=3]

[ext_resource type="SpriteFrames" path="${base}_frames.tres" id="1_frames"]
${character ? `[ext_resource type="Script" path="${base}.gd" id="2_script"]\n` : ''}
[sub_resource type="RectangleShape2D" id="RectangleShape2D_feet"]
size = Vector2(${Math.round(doc.size * 0.4)}, ${Math.max(4, Math.round(doc.size * 0.18))})

[node name="${node}" type="${character ? 'CharacterBody2D' : 'StaticBody2D'}"]
y_sort_enabled = true
${character ? 'motion_mode = 1\nscript = ExtResource("2_script")\n' : ''}
[node name="AnimatedSprite2D" type="AnimatedSprite2D" parent="."]
texture_filter = 1
offset = Vector2(0, ${offY})
sprite_frames = ExtResource("1_frames")
animation = &"${first}"
autoplay = "${first}"

[node name="CollisionShape2D" type="CollisionShape2D" parent="."]
position = Vector2(0, ${-Math.max(2, Math.round(doc.size * 0.09))})
shape = SubResource("RectangleShape2D_feet")
`;
}

function readme(doc: SpriteDoc, base: string, meta: SheetMeta): string {
  const list = meta.animations.map((a) => `- \`${a.name}\` – ${a.frames} Frames, ${a.fps} fps${a.loop ? ', Schleife' : ''}`).join('\n');
  return `# ${doc.name} – aus MapForge

## Godot 4 (3 Schritte)

1. Diesen Ordner \`${base}/\` in dein Godot-Projekt ziehen (egal wohin).
2. \`${base}.tscn\` in deine Szene ziehen – fertig.
3. ${doc.kind === 'character' ? 'Starten: Pfeiltasten bewegen die Figur, "walk" / "idle" laufen automatisch.' : 'Das Objekt spielt seine erste Animation automatisch ab.'}

Pixel bleiben scharf (Filter "Nearest" ist gesetzt). Die Füße liegen am Ursprung des Knotens –
passt zu Y-Sort und zur MapForge-Karte.

## Andere Engines (Unity, GDevelop, Phaser …)

- \`${base}.png\` – Spritesheet, eine Zeile pro Animation, Frame-Größe ${meta.frameWidth} × ${meta.frameHeight} px
- \`${base}.json\` – Zeilen, Frame-Anzahl, fps, Schleife

## Animationen

${list}
`;
}

export function exportSpriteGodot(doc: SpriteDoc, anims: AnimDef[], fps: Fps) {
  const base = safeFileName(doc.name) || 'sprite';
  const { canvas, meta } = sheet(doc, anims, fps);
  const feet = feetRow(doc);
  const entries: ZipEntry[] = [
    { path: `${base}/${base}.png`, data: pngBytes(canvas) },
    { path: `${base}/${base}.json`, data: JSON.stringify(meta, null, 1) },
    { path: `${base}/${base}_frames.tres`, data: godotFrames(`${base}.png`, meta) },
    { path: `${base}/${base}.tscn`, data: godotScene(doc, base, meta, feet) },
    { path: `${base}/README.md`, data: readme(doc, base, meta) },
    { path: `${base}/${base}_still.png`, data: dataUrlToBytes(toPng(compose(doc), doc.size)) },
  ];
  if (doc.kind === 'character') entries.push({ path: `${base}/${base}.gd`, data: PLAYER_SCRIPT });
  downloadBlob(createZip(entries), `${base}-godot.zip`);
}

/** frames of a sheet as separate PNGs (for engines / tools that want single images) */
export function exportFramesZip(doc: SpriteDoc, anims: AnimDef[], fps: Fps) {
  const base = safeFileName(doc.name) || 'sprite';
  const { canvas, meta } = sheet(doc, anims, fps);
  const n = frameSize(doc.size);
  const entries: ZipEntry[] = [];
  for (const a of meta.animations)
    for (let i = 0; i < a.frames; i++) {
      const c = document.createElement('canvas');
      c.width = c.height = n;
      c.getContext('2d')!.drawImage(canvas, i * n, a.row * n, n, n, 0, 0, n, n);
      entries.push({ path: `${base}/${a.name}_${String(i).padStart(2, '0')}.png`, data: pngBytes(c) });
    }
  entries.push({ path: `${base}/${base}.json`, data: JSON.stringify(meta, null, 1) });
  downloadBlob(createZip(entries), `${base}-frames.zip`);
}
