import type { CustomAnim, SpriteDoc, View } from './types';
import { buildSheet, feetInFrame, framePad, frameSize, type AnimDef } from './animation';
import { compose, toPng } from './store';
import { createZip, type ZipEntry } from '../export/zip';
import { dataUrlToBytes, downloadBlob, safeFileName } from '../utils/download';

// Export of characters / objects: spritesheet PNG, JSON (any engine) and a ready Godot 4
// folder – copy it into the project, drag the .tscn into a scene, done.

export interface SheetMeta {
  name: string;
  frameWidth: number;
  frameHeight: number;
  columns: number;
  animations: { name: string; row: number; frames: number; fps: number; loop: boolean }[];
}

export type Fps = Record<string, number>;

function sheet(doc: SpriteDoc, anims: AnimDef[], fps: Fps, views: View[] = ['front'], custom: CustomAnim[] = []) {
  const { canvas, rows, cols } = buildSheet(doc, anims, views, custom, fps);
  const meta: SheetMeta = {
    name: doc.name,
    frameWidth: frameSize(doc.size),
    frameHeight: frameSize(doc.size),
    columns: cols,
    animations: rows.map((r) => ({ name: r.name, row: r.row, frames: r.frames, fps: r.fps, loop: r.loop })),
  };
  return { canvas, meta };
}

const pngBytes = (c: HTMLCanvasElement) => dataUrlToBytes(c.toDataURL('image/png'));

/** lowest opaque row of the still image = feet line */
export function feetRow(doc: SpriteDoc): number {
  const img = compose({ ...doc, layers: doc.layers.filter((l) => l.slot !== 'shadow') });
  for (let y = doc.size - 1; y >= 0; y--) for (let x = 0; x < doc.size; x++) if (img[(y * doc.size + x) * 4 + 3] > 0) return y;
  return doc.size - 1;
}

export interface ExportChoice {
  anims: AnimDef[];
  fps: Fps;
  views: View[];
  custom: CustomAnim[];
}

const feetOf = (doc: SpriteDoc) => (doc.kind === 'object' ? feetRow(doc) + framePad(doc.size) : feetInFrame(doc));

export function exportSheetPng(doc: SpriteDoc, c0: ExportChoice, scale = 1) {
  const { canvas } = sheet(doc, c0.anims, c0.fps, c0.views, c0.custom);
  let c = canvas;
  if (scale > 1) {
    c = document.createElement('canvas');
    c.width = canvas.width * scale;
    c.height = canvas.height * scale;
    const g = c.getContext('2d')!;
    g.imageSmoothingEnabled = false;
    g.drawImage(canvas, 0, 0, c.width, c.height);
  }
  downloadBlob(new Blob([pngBytes(c) as BlobPart], { type: 'image/png' }), `${safeFileName(doc.name)}-sheet${scale > 1 ? `@${scale}x` : ''}.png`);
}

function godotFrames(file: string, meta: SheetMeta): string {
  const subs: string[] = [];
  const anims: string[] = [];
  let id = 0;
  for (const a of meta.animations) {
    const frames: string[] = [];
    for (let i = 0; i < a.frames; i++) {
      const sid = `AtlasTexture_${id++}`;
      subs.push(`[sub_resource type="AtlasTexture" id="${sid}"]\natlas = ExtResource("1_sheet")\nregion = Rect2(${i * meta.frameWidth}, ${a.row * meta.frameHeight}, ${meta.frameWidth}, ${meta.frameHeight})\n`);
      frames.push(`{\n"duration": 1.0,\n"texture": SubResource("${sid}")\n}`);
    }
    anims.push(`{\n"frames": [${frames.join(', ')}],\n"loop": ${a.loop},\n"name": &"${a.name}",\n"speed": ${a.fps.toFixed(1)}\n}`);
  }
  return `[gd_resource type="SpriteFrames" load_steps=${subs.length + 2} format=3]

[ext_resource type="Texture2D" path="${file}" id="1_sheet"]

${subs.join('\n')}
[resource]
animations = [${anims.join(', ')}]
`;
}

const PLAYER_SCRIPT = `extends CharacterBody2D
## Player, generated by MapForge – ready to play:
##   Arrow keys (ui_left/right/up/down) walk, Shift runs, Space/Enter (ui_accept) or J attacks.
##   Enemies (group "enemy") in front of the figure are hit with hurt(damage).
##   Call hurt(damage) on the player from your own code – at 0 hp it plays "death".
## Uses walk_down / walk_side / walk_up (+ walk_down_side / walk_up_side for 8 directions)
## when directions were exported, else walk, idle …
## One-shot animations (attack, hurt, death, jump …) play once, then control returns.

signal hp_changed(hp: int)
signal died

@export var speed := 90.0
@export var run_speed := 150.0
@export var max_hp := 5
@export var attack_damage := 1
@export var attack_reach := 22.0
@onready var sprite: AnimatedSprite2D = $AnimatedSprite2D
var facing := "down"
var ahead := Vector2.DOWN
var hp := 5
var busy := ""  # one-shot animation that is playing ("" = free to move)

func _ready() -> void:
\tadd_to_group("player")
\thp = max_hp
\tsprite.animation_finished.connect(_on_finished)

func _physics_process(_delta: float) -> void:
\tif busy == "death":
\t\treturn
\tvar dir := Vector2.ZERO
\tif busy == "":
\t\tdir = Input.get_vector("ui_left", "ui_right", "ui_up", "ui_down")
\tvar running := Input.is_key_pressed(KEY_SHIFT) and _has("run")
\tvelocity = dir * (run_speed if running else speed)
\tmove_and_slide()
\tif dir != Vector2.ZERO:
\t\t_face(dir)
\tif busy != "":
\t\treturn
\tif (Input.is_action_just_pressed("ui_accept") or Input.is_key_pressed(KEY_J)) and _has("attack"):
\t\tattack()
\telif dir != Vector2.ZERO:
\t\tplay_anim("run" if running else "walk")
\telse:
\t\tplay_anim("idle")

func attack() -> void:
\tbusy = "attack"
\tplay_anim("attack")
\tvar fwd := _facing_vector()
\tfor e in get_tree().get_nodes_in_group("enemy"):
\t\tvar n := e as Node2D
\t\tif n == null or not n.has_method("hurt"):
\t\t\tcontinue
\t\tvar to := n.global_position - global_position
\t\tif to.length() < attack_reach and to.normalized().dot(fwd) > 0.3:
\t\t\tn.call("hurt", attack_damage, global_position)

func hurt(damage := 1, from := Vector2.ZERO) -> void:
\tif busy == "death":
\t\treturn
\thp = maxi(hp - damage, 0)
\thp_changed.emit(hp)
\tif from != Vector2.ZERO:
\t\tposition += (global_position - from).normalized() * 6.0
\tif hp == 0:
\t\tbusy = "death"
\t\tplay_anim("death")
\t\tdied.emit()
\telif _has("hurt"):
\t\tbusy = "hurt"
\t\tplay_anim("hurt")

func play_anim(base: String) -> void:
\tvar anim := _name(base)
\tif anim != "" and (sprite.animation != anim or not sprite.is_playing()):
\t\tsprite.play(anim)

func _on_finished() -> void:
\tif busy != "death":
\t\tbusy = ""

func _face(dir: Vector2) -> void:
\t# 8 directions when the diagonals (…_down_side / …_up_side) were exported, else 4
\tif _diagonal():
\t\tvar o := posmod(roundi(dir.angle() / (PI / 4.0)), 8)  # 0 → 1 ↘ 2 ↓ … 6 ↑ 7 ↗
\t\tfacing = ["side", "down_side", "down", "down_side", "side", "up_side", "up", "up_side"][o]
\t\tsprite.flip_h = o >= 3 and o <= 5
\t\tahead = Vector2.RIGHT.rotated(o * PI / 4.0)
\telif absf(dir.x) > absf(dir.y):
\t\tfacing = "side"
\t\tsprite.flip_h = dir.x < 0.0
\t\tahead = Vector2.LEFT if sprite.flip_h else Vector2.RIGHT
\telse:
\t\tfacing = "down" if dir.y > 0.0 else "up"
\t\tsprite.flip_h = false
\t\tahead = Vector2.DOWN if facing == "down" else Vector2.UP

func _diagonal() -> bool:
\tfor n in sprite.sprite_frames.get_animation_names():
\t\tif n.ends_with("_down_side"):
\t\t\treturn true
\treturn false

func _facing_vector() -> Vector2:
\treturn ahead

func _name(base: String) -> String:
\tfor n in [base + "_" + facing, base + "_" + facing.get_slice("_", 0), base + "_down", base]:
\t\tif sprite.sprite_frames.has_animation(n):
\t\t\treturn n
\treturn ""

func _has(base: String) -> bool:
\treturn _name(base) != ""
`;

const PLATFORMER_SCRIPT = `extends CharacterBody2D
## Platformer player, generated by MapForge (side view) – ready to play:
##   ← → walk, Shift runs, ↑ / Space / Enter jumps (hold = higher), J or X attacks.
##   Ladders (Area2D in group "ladder"): ↑ / ↓ climb, jump off sideways.
##   ↓ + jump drops through one-way platforms.
##   Hazards call hazard_hit(): lose 1 hp and restart at the last safe spot. Same when
##   falling below fall_limit. Call hurt(damage) from your own code – at 0 hp "death".
##   Enemies (group "enemy") in front are hit with hurt(damage).
## Animations: idle, walk, run, jump, fall, attack, hurt, death, climb (with _side), whatever exists.

signal hp_changed(hp: int)
signal died

@export var speed := 90.0
@export var run_speed := 150.0
@export var jump_velocity := -260.0
@export var gravity := 700.0
@export var climb_speed := 80.0
@export var max_hp := 5
@export var attack_damage := 1
@export var attack_reach := 22.0
## below this y the figure counts as fallen (the MapForge loader sets it)
@export var fall_limit := 100000.0
@onready var sprite: AnimatedSprite2D = $AnimatedSprite2D
var hp := 5
var busy := ""
var climbing := false
var coyote := 0.0
var jump_cut := false
var safe_position := Vector2.ZERO
var safe_timer := 0.0

func _ready() -> void:
\tadd_to_group("player")
\thp = max_hp
\tsafe_position = global_position
\tsprite.animation_finished.connect(_on_finished)

func _physics_process(delta: float) -> void:
\tif busy == "death":
\t\tvelocity.x = 0.0
\t\tvelocity.y += gravity * delta
\t\tmove_and_slide()
\t\treturn
\tvar dir := 0.0
\tif busy == "":
\t\tdir = Input.get_axis("ui_left", "ui_right")
\tvar running := Input.is_key_pressed(KEY_SHIFT) and _has("run")
\tvar jump_pressed := Input.is_action_just_pressed("ui_accept") or (Input.is_action_just_pressed("ui_up") and not _on_ladder())
\tvar jump_held := Input.is_action_pressed("ui_accept") or Input.is_action_pressed("ui_up")

\t# ladders
\tvar on_ladder := _on_ladder()
\tif on_ladder and busy == "" and (Input.is_action_pressed("ui_up") or (Input.is_action_pressed("ui_down") and not is_on_floor())):
\t\tclimbing = true
\tif climbing and (not on_ladder or (Input.is_action_just_pressed("ui_accept") and dir != 0.0)):
\t\tclimbing = false
\t\tif Input.is_action_just_pressed("ui_accept"):
\t\t\tvelocity.y = jump_velocity * 0.8
\tif climbing:
\t\tvelocity = Vector2(dir * speed * 0.5, Input.get_axis("ui_up", "ui_down") * climb_speed)
\t\tmove_and_slide()
\t\tif is_on_floor() and not Input.is_action_pressed("ui_up"):
\t\t\tclimbing = false
\t\t_face(dir)
\t\tif _has("climb"):
\t\t\tif velocity.length() > 1.0:
\t\t\t\tplay_anim("climb")
\t\t\telse:
\t\t\t\tsprite.pause()
\t\telse:
\t\t\tplay_anim("idle")
\t\treturn

\tif is_on_floor():
\t\tcoyote = 0.1
\telse:
\t\tcoyote = maxf(coyote - delta, 0.0)
\t\tvelocity.y += gravity * delta
\tvelocity.x = dir * (run_speed if running else speed)
\tif busy == "" and jump_pressed:
\t\tif Input.is_action_pressed("ui_down") and is_on_floor():
\t\t\tposition.y += 5.0  # drop through a one-way platform
\t\telif coyote > 0.0:
\t\t\tvelocity.y = jump_velocity
\t\t\tcoyote = 0.0
\t\t\tjump_cut = false
\tif not jump_held and velocity.y < 0.0 and not jump_cut:
\t\tvelocity.y *= 0.5
\t\tjump_cut = true
\tmove_and_slide()
\t_face(dir)

\t# remember a safe spot, fall out of the level
\tsafe_timer -= delta
\tif is_on_floor() and safe_timer <= 0.0:
\t\tsafe_position = global_position
\t\tsafe_timer = 0.4
\tif global_position.y > fall_limit:
\t\thazard_hit()
\t\treturn

\tif busy != "":
\t\treturn
\tif (Input.is_key_pressed(KEY_J) or Input.is_key_pressed(KEY_X)) and _has("attack"):
\t\tattack()
\telif not is_on_floor():
\t\tif velocity.y > 0.0 and _has("fall"):
\t\t\tplay_anim("fall")
\t\telif _has("jump"):
\t\t\t_hold("jump", 2 if velocity.y < -60.0 else 3)
\telif dir != 0.0:
\t\tplay_anim("run" if running or not _has("walk") else "walk")
\telse:
\t\tplay_anim("idle")

func attack() -> void:
\tbusy = "attack"
\tplay_anim("attack")
\tvar ahead := Vector2.LEFT if sprite.flip_h else Vector2.RIGHT
\tfor e in get_tree().get_nodes_in_group("enemy"):
\t\tvar n := e as Node2D
\t\tif n == null or not n.has_method("hurt"):
\t\t\tcontinue
\t\tvar to := n.global_position - global_position
\t\tif to.length() < attack_reach and to.normalized().dot(ahead) > 0.3:
\t\t\tn.call("hurt", attack_damage, global_position)

func hurt(damage := 1, from := Vector2.ZERO) -> void:
\tif busy == "death":
\t\treturn
\thp = maxi(hp - damage, 0)
\thp_changed.emit(hp)
\tif from != Vector2.ZERO:
\t\tvelocity.x = signf(global_position.x - from.x) * 120.0
\tif hp == 0:
\t\tbusy = "death"
\t\tclimbing = false
\t\tplay_anim("death")
\t\tdied.emit()
\telif _has("hurt"):
\t\tbusy = "hurt"
\t\tplay_anim("hurt")

## spikes, water, lava or a fall: lose 1 hp and continue at the last safe spot
func hazard_hit() -> void:
\tif busy == "death":
\t\treturn
\tglobal_position = safe_position
\tvelocity = Vector2.ZERO
\tclimbing = false
\thurt(1)

func play_anim(base: String) -> void:
\tvar anim := _name(base)
\tif anim != "" and (sprite.animation != anim or not sprite.is_playing()):
\t\tsprite.play(anim)

## show one frame of an animation (jump: rising / top)
func _hold(base: String, frame: int) -> void:
\tvar anim := _name(base)
\tif sprite.animation != anim:
\t\tsprite.animation = anim
\tsprite.pause()
\tsprite.frame = mini(frame, sprite.sprite_frames.get_frame_count(anim) - 1)

func _on_finished() -> void:
\tif busy != "death":
\t\tbusy = ""

func _face(dir: float) -> void:
\tif dir != 0.0:
\t\tsprite.flip_h = dir < 0.0

func _on_ladder() -> bool:
\tfor a in get_tree().get_nodes_in_group("ladder"):
\t\tvar area := a as Area2D
\t\tif area and area.overlaps_body(self):
\t\t\treturn true
\treturn false

func _name(base: String) -> String:
\tfor n in [base + "_side", base]:
\t\tif sprite.sprite_frames.has_animation(n):
\t\t\treturn n
\treturn ""

func _has(base: String) -> bool:
\treturn _name(base) != ""
`;

const ENEMY_SCRIPT = `extends CharacterBody2D
## Enemy, generated by MapForge: waits, chases the player (group "player") when near and
## attacks when close (calls hurt() on the player). Takes hits via hurt(damage), plays
## "hurt", and at 0 hp "death" – then it is removed.
## Moves with the first animation that exists (fly, hop, crawl, walk), "idle" otherwise –
## with directions (fly_down / fly_side / fly_up …) when they were exported.

signal died

@export var speed := 45.0
@export var sight := 140.0
@export var max_hp := 3
@export var damage := 1
@export var attack_reach := 16.0
@export var attack_pause := 1.0
@onready var sprite: AnimatedSprite2D = $AnimatedSprite2D
var facing := "down"
var ahead := Vector2.DOWN
var hp := 3
var busy := ""
var cooldown := 0.0

func _ready() -> void:
\tadd_to_group("enemy")
\thp = max_hp
\tsprite.animation_finished.connect(_on_finished)

func _physics_process(delta: float) -> void:
\tcooldown = maxf(cooldown - delta, 0.0)
\tif busy != "":
\t\treturn
\tvar target: Node2D = get_tree().get_first_node_in_group("player")
\tvar dir := Vector2.ZERO
\tif target and global_position.distance_to(target.global_position) < sight:
\t\tdir = global_position.direction_to(target.global_position)
\t\tif global_position.distance_to(target.global_position) < attack_reach and cooldown == 0.0:
\t\t\t_face(dir)
\t\t\tbusy = "attack"
\t\t\tcooldown = attack_pause
\t\t\t_play("attack")
\t\t\tif target.has_method("hurt"):
\t\t\t\ttarget.call("hurt", damage, global_position)
\t\t\treturn
\tvelocity = dir * speed
\tmove_and_slide()
\tif dir != Vector2.ZERO:
\t\t_face(dir)
\tvar base := "idle"
\tif dir != Vector2.ZERO:
\t\tfor a in ["fly", "hop", "crawl", "walk"]:
\t\t\tif _has(a):
\t\t\t\tbase = a
\t\t\t\tbreak
\t_play(base)

func hurt(amount := 1, from := Vector2.ZERO) -> void:
\tif busy == "death":
\t\treturn
\thp -= amount
\tif from != Vector2.ZERO:
\t\tposition += (global_position - from).normalized() * 8.0
\tif hp <= 0:
\t\tbusy = "death"
\t\t\$CollisionShape2D.set_deferred("disabled", true)
\t\tdied.emit()
\t\tif _has("death"):
\t\t\t_play("death")
\t\telse:
\t\t\tqueue_free()
\telif _has("hurt"):
\t\tbusy = "hurt"
\t\t_play("hurt")

func _on_finished() -> void:
\tif busy == "death":
\t\tqueue_free()
\telse:
\t\tbusy = ""

func _play(base: String) -> void:
\tvar anim := _name(base)
\tif anim != "" and (sprite.animation != anim or not sprite.is_playing()):
\t\tsprite.play(anim)
\telif anim == "" and busy != "death":
\t\tbusy = ""

func _face(dir: Vector2) -> void:
\t# 8 directions when the diagonals (…_down_side / …_up_side) were exported, else 4
\tif _diagonal():
\t\tvar o := posmod(roundi(dir.angle() / (PI / 4.0)), 8)  # 0 → 1 ↘ 2 ↓ … 6 ↑ 7 ↗
\t\tfacing = ["side", "down_side", "down", "down_side", "side", "up_side", "up", "up_side"][o]
\t\tsprite.flip_h = o >= 3 and o <= 5
\t\tahead = Vector2.RIGHT.rotated(o * PI / 4.0)
\telif absf(dir.x) > absf(dir.y):
\t\tfacing = "side"
\t\tsprite.flip_h = dir.x < 0.0
\t\tahead = Vector2.LEFT if sprite.flip_h else Vector2.RIGHT
\telse:
\t\tfacing = "down" if dir.y > 0.0 else "up"
\t\tsprite.flip_h = false
\t\tahead = Vector2.DOWN if facing == "down" else Vector2.UP

func _diagonal() -> bool:
\tfor n in sprite.sprite_frames.get_animation_names():
\t\tif n.ends_with("_down_side"):
\t\t\treturn true
\treturn false

func _name(base: String) -> String:
\tfor n in [base + "_" + facing, base + "_" + facing.get_slice("_", 0), base + "_down", base]:
\t\tif sprite.sprite_frames.has_animation(n):
\t\t\treturn n
\treturn ""

func _has(base: String) -> bool:
\treturn _name(base) != ""
`;

/** Godot scene for a sprite: feetInFrame = feet row inside one frame (frames are square). */
function godotScene(name: string, character: boolean, frame: number, feetInFrame: number, spriteSize: number, base: string, meta: SheetMeta, platformer = false): string {
  const node = name.replace(/[^\p{L}\p{N}_]/gu, '_') || 'Sprite';
  const first = meta.animations.find((a) => a.name === 'idle' || a.name === 'idle_down')?.name ?? meta.animations[0]?.name ?? 'default';
  // feet of the sprite at the node origin (y-sort / collision work from the feet)
  const offY = -(feetInFrame + 1 - frame / 2);
  return `[gd_scene load_steps=${character ? 4 : 3} format=3]

[ext_resource type="SpriteFrames" path="${base}_frames.tres" id="1_frames"]
${character ? `[ext_resource type="Script" path="${base}.gd" id="2_script"]\n` : ''}
[sub_resource type="RectangleShape2D" id="RectangleShape2D_feet"]
size = Vector2(${Math.round(spriteSize * 0.4)}, ${Math.max(4, Math.round(spriteSize * 0.18))})

[node name="${node}" type="${character ? 'CharacterBody2D' : 'StaticBody2D'}"]
y_sort_enabled = true
${character ? `${platformer ? '' : 'motion_mode = 1\n'}script = ExtResource("2_script")\n` : ''}
[node name="AnimatedSprite2D" type="AnimatedSprite2D" parent="."]
texture_filter = 1
offset = Vector2(0, ${offY})
sprite_frames = ExtResource("1_frames")
animation = &"${first}"
autoplay = "${first}"

[node name="CollisionShape2D" type="CollisionShape2D" parent="."]
position = Vector2(0, ${-Math.max(2, Math.round(spriteSize * 0.09))})
shape = SubResource("RectangleShape2D_feet")
`;
}

/** Files of a Godot sprite folder (sheet, SpriteFrames, scene, script, JSON). */
export function spriteGodotEntries(o: { folder: string; base: string; name: string; character: boolean; enemy?: boolean; platformer?: boolean; png: Uint8Array; meta: SheetMeta; feetInFrame: number; spriteSize: number }): ZipEntry[] {
  const { folder, base, meta } = o;
  const entries: ZipEntry[] = [
    { path: `${folder}/${base}.png`, data: o.png },
    { path: `${folder}/${base}.json`, data: JSON.stringify(meta, null, 1) },
    { path: `${folder}/${base}_frames.tres`, data: godotFrames(`${base}.png`, meta) },
    { path: `${folder}/${base}.tscn`, data: godotScene(o.name, o.character, meta.frameWidth, o.feetInFrame, o.spriteSize, base, meta, o.platformer && !o.enemy) },
  ];
  if (o.character) entries.push({ path: `${folder}/${base}.gd`, data: o.enemy ? ENEMY_SCRIPT : o.platformer ? PLATFORMER_SCRIPT : PLAYER_SCRIPT });
  return entries;
}

function readme(doc: SpriteDoc, base: string, meta: SheetMeta, platformer = false): string {
  const list = meta.animations.map((a) => `- \`${a.name}\` – ${a.frames} Frames, ${a.fps} fps${a.loop ? ', Schleife' : ''}`).join('\n');
  return `# ${doc.name} – aus MapForge

## Godot 4 (3 Schritte)

1. Diesen Ordner \`${base}/\` in dein Godot-Projekt ziehen (egal wohin).
2. \`${base}.tscn\` in deine Szene ziehen – fertig.
3. ${platformer ? 'Starten (Seitenansicht / Platformer): ← → laufen, Shift rennt, ↑ / Leertaste springt, J oder X greift an. Braucht einen Boden mit Kollision. "idle" / "walk" / "run" / "jump" / "fall" / "attack" laufen automatisch; Schaden: hurt(1) am Spieler aufrufen.' : doc.kind === 'character' ? 'Starten: Pfeiltasten laufen, Shift rennt, Leertaste/Enter oder J greift an (trifft Gegner der Gruppe "enemy" vor der Figur). "walk" / "run" / "idle" / "attack" (mit Richtungen) laufen automatisch. Schaden: hurt(1) am Spieler aufrufen – bei 0 Leben spielt "death".' : doc.kind === 'creature' ? 'Starten: der Gegner wartet, verfolgt die Spielfigur (Gruppe "player"), greift in Reichweite an, spielt bei Treffern "hurt" und verschwindet nach "death". Leben, Tempo und Schaden im Inspector einstellbar.' : 'Das Objekt spielt seine erste Animation automatisch ab.'}

Pixel bleiben scharf (Filter "Nearest" ist gesetzt). Die Füße liegen am Ursprung des Knotens –
passt zu Y-Sort und zur MapForge-Karte.

## Andere Engines (Unity, GDevelop, Phaser …)

- \`${base}.png\` – Spritesheet, eine Zeile pro Animation, Frame-Größe ${meta.frameWidth} × ${meta.frameHeight} px
- \`${base}.json\` – Zeilen, Frame-Anzahl, fps, Schleife

## Animationen

${list}
`;
}

/** only the side view exported → the figure is for a side-scroller (gravity, jumping) */
export const isPlatformer = (doc: SpriteDoc, c: ExportChoice) => doc.kind === 'character' && c.views.length === 1 && c.views[0] === 'side';

export function exportSpriteGodot(doc: SpriteDoc, c0: ExportChoice) {
  const base = safeFileName(doc.name) || 'sprite';
  const platformer = isPlatformer(doc, c0);
  const { canvas, meta } = sheet(doc, c0.anims, c0.fps, c0.views, c0.custom);
  const entries: ZipEntry[] = [
    ...spriteGodotEntries({ folder: base, base, name: doc.name, character: doc.kind !== 'object', enemy: doc.kind === 'creature', platformer, png: pngBytes(canvas), meta, feetInFrame: feetOf(doc), spriteSize: doc.size }),
    { path: `${base}/README.md`, data: readme(doc, base, meta, platformer) },
    { path: `${base}/${base}_still.png`, data: dataUrlToBytes(toPng(compose(doc), doc.size)) },
  ];
  downloadBlob(createZip(entries), `${base}-godot.zip`);
}

/** frames of a sheet as separate PNGs (for engines / tools that want single images) */
export function exportFramesZip(doc: SpriteDoc, c0: ExportChoice) {
  const base = safeFileName(doc.name) || 'sprite';
  const { canvas, meta } = sheet(doc, c0.anims, c0.fps, c0.views, c0.custom);
  const n = frameSize(doc.size);
  const entries: ZipEntry[] = [];
  for (const a of meta.animations)
    for (let i = 0; i < a.frames; i++) {
      const c = document.createElement('canvas');
      c.width = c.height = n;
      c.getContext('2d')!.drawImage(canvas, i * n, a.row * n, n, n, 0, 0, n, n);
      entries.push({ path: `${base}/${a.name}_${String(i).padStart(2, '0')}.png`, data: pngBytes(c) });
    }
  entries.push({ path: `${base}/${base}.json`, data: JSON.stringify(meta, null, 1) });
  downloadBlob(createZip(entries), `${base}-frames.zip`);
}
