import type { CustomAnim, SpriteDoc, View } from './types';
import { buildSheet, feetInFrame, framePad, frameSize, type AnimDef } from './animation';
import { compose, toPng } from './store';
import { createZip, type ZipEntry } from '../export/zip';
import { dataUrlToBytes, downloadBlob, safeFileName } from '../utils/download';

// Export of characters / objects: spritesheet PNG, JSON (any engine) and a ready Godot 4
// folder – copy it into the project, drag the .tscn into a scene, done.

export interface SheetMeta {
  name: string;
  frameWidth: number;
  frameHeight: number;
  columns: number;
  animations: { name: string; row: number; frames: number; fps: number; loop: boolean }[];
}

export type Fps = Record<string, number>;

function sheet(doc: SpriteDoc, anims: AnimDef[], fps: Fps, views: View[] = ['front'], custom: CustomAnim[] = []) {
  const { canvas, rows, cols } = buildSheet(doc, anims, views, custom, fps);
  const meta: SheetMeta = {
    name: doc.name,
    frameWidth: frameSize(doc.size),
    frameHeight: frameSize(doc.size),
    columns: cols,
    animations: rows.map((r) => ({ name: r.name, row: r.row, frames: r.frames, fps: r.fps, loop: r.loop })),
  };
  return { canvas, meta };
}

const pngBytes = (c: HTMLCanvasElement) => dataUrlToBytes(c.toDataURL('image/png'));

/** lowest opaque row of the still image = feet line */
export function feetRow(doc: SpriteDoc): number {
  const img = compose({ ...doc, layers: doc.layers.filter((l) => l.slot !== 'shadow') });
  for (let y = doc.size - 1; y >= 0; y--) for (let x = 0; x < doc.size; x++) if (img[(y * doc.size + x) * 4 + 3] > 0) return y;
  return doc.size - 1;
}

export interface ExportChoice {
  anims: AnimDef[];
  fps: Fps;
  views: View[];
  custom: CustomAnim[];
}

const feetOf = (doc: SpriteDoc) => (doc.kind === 'object' ? feetRow(doc) + framePad(doc.size) : feetInFrame(doc));

export function exportSheetPng(doc: SpriteDoc, c0: ExportChoice, scale = 1) {
  const { canvas } = sheet(doc, c0.anims, c0.fps, c0.views, c0.custom);
  let c = canvas;
  if (scale > 1) {
    c = document.createElement('canvas');
    c.width = canvas.width * scale;
    c.height = canvas.height * scale;
    const g = c.getContext('2d')!;
    g.imageSmoothingEnabled = false;
    g.drawImage(canvas, 0, 0, c.width, c.height);
  }
  downloadBlob(new Blob([pngBytes(c) as BlobPart], { type: 'image/png' }), `${safeFileName(doc.name)}-sheet${scale > 1 ? `@${scale}x` : ''}.png`);
}

function godotFrames(file: string, meta: SheetMeta): string {
  const subs: string[] = [];
  const anims: string[] = [];
  let id = 0;
  for (const a of meta.animations) {
    const frames: string[] = [];
    for (let i = 0; i < a.frames; i++) {
      const sid = `AtlasTexture_${id++}`;
      subs.push(`[sub_resource type="AtlasTexture" id="${sid}"]\natlas = ExtResource("1_sheet")\nregion = Rect2(${i * meta.frameWidth}, ${a.row * meta.frameHeight}, ${meta.frameWidth}, ${meta.frameHeight})\n`);
      frames.push(`{\n"duration": 1.0,\n"texture": SubResource("${sid}")\n}`);
    }
    anims.push(`{\n"frames": [${frames.join(', ')}],\n"loop": ${a.loop},\n"name": &"${a.name}",\n"speed": ${a.fps.toFixed(1)}\n}`);
  }
  return `[gd_resource type="SpriteFrames" load_steps=${subs.length + 2} format=3]

[ext_resource type="Texture2D" path="${file}" id="1_sheet"]

${subs.join('\n')}
[resource]
animations = [${anims.join(', ')}]
`;
}

const PLAYER_SCRIPT = `extends CharacterBody2D
## Top-down movement, generated by MapForge.
## Arrow keys (ui_left / ui_right / ui_up / ui_down). Plays "walk" while moving, "idle" otherwise –
## with directions (walk_down / walk_side / walk_up …) when they were exported.

@export var speed := 90.0
@onready var sprite: AnimatedSprite2D = $AnimatedSprite2D
var facing := "down"

func _ready() -> void:
\tadd_to_group("player")

func _physics_process(_delta: float) -> void:
\tvar dir := Input.get_vector("ui_left", "ui_right", "ui_up", "ui_down")
\tvelocity = dir * speed
\tmove_and_slide()
\tif dir != Vector2.ZERO:
\t\tif absf(dir.x) > absf(dir.y):
\t\t\tfacing = "side"
\t\t\tsprite.flip_h = dir.x < 0.0
\t\telse:
\t\t\tfacing = "down" if dir.y > 0.0 else "up"
\t\t\tsprite.flip_h = false
\tplay_anim("walk" if dir != Vector2.ZERO else "idle")

func play_anim(base: String) -> void:
\tvar anim := base + "_" + facing
\tif not sprite.sprite_frames.has_animation(anim):
\t\tanim = base + "_down" if sprite.sprite_frames.has_animation(base + "_down") else base
\tif sprite.sprite_frames.has_animation(anim) and sprite.animation != anim:
\t\tsprite.play(anim)
`;

const ENEMY_SCRIPT = `extends CharacterBody2D
## Simple enemy, generated by MapForge: waits, chases the player (group "player") when near.
## Uses the first move animation that exists (fly, hop, crawl, walk) and "idle" otherwise –
## with directions (fly_down / fly_side / fly_up …) when they were exported.

@export var speed := 45.0
@export var sight := 140.0
@onready var sprite: AnimatedSprite2D = $AnimatedSprite2D
var facing := "down"

func _physics_process(_delta: float) -> void:
\tvar target: Node2D = get_tree().get_first_node_in_group("player")
\tvar dir := Vector2.ZERO
\tif target and global_position.distance_to(target.global_position) < sight:
\t\tdir = global_position.direction_to(target.global_position)
\tvelocity = dir * speed
\tmove_and_slide()
\tif dir != Vector2.ZERO:
\t\tif absf(dir.x) > absf(dir.y):
\t\t\tfacing = "side"
\t\t\tsprite.flip_h = dir.x < 0.0
\t\telse:
\t\t\tfacing = "down" if dir.y > 0.0 else "up"
\t\t\tsprite.flip_h = false
\tvar base := "idle"
\tif dir != Vector2.ZERO:
\t\tfor a in ["fly", "hop", "crawl", "walk"]:
\t\t\tif _has(a):
\t\t\t\tbase = a
\t\t\t\tbreak
\tvar anim := _name(base)
\tif anim != "" and sprite.animation != anim:
\t\tsprite.play(anim)

func _name(base: String) -> String:
\tfor n in [base + "_" + facing, base + "_down", base]:
\t\tif sprite.sprite_frames.has_animation(n):
\t\t\treturn n
\treturn ""

func _has(base: String) -> bool:
\treturn _name(base) != ""
`;

/** Godot scene for a sprite: feetInFrame = feet row inside one frame (frames are square). */
function godotScene(name: string, character: boolean, frame: number, feetInFrame: number, spriteSize: number, base: string, meta: SheetMeta): string {
  const node = name.replace(/[^\p{L}\p{N}_]/gu, '_') || 'Sprite';
  const first = meta.animations.find((a) => a.name === 'idle' || a.name === 'idle_down')?.name ?? meta.animations[0]?.name ?? 'default';
  // feet of the sprite at the node origin (y-sort / collision work from the feet)
  const offY = -(feetInFrame + 1 - frame / 2);
  return `[gd_scene load_steps=${character ? 4 : 3} format=3]

[ext_resource type="SpriteFrames" path="${base}_frames.tres" id="1_frames"]
${character ? `[ext_resource type="Script" path="${base}.gd" id="2_script"]\n` : ''}
[sub_resource type="RectangleShape2D" id="RectangleShape2D_feet"]
size = Vector2(${Math.round(spriteSize * 0.4)}, ${Math.max(4, Math.round(spriteSize * 0.18))})

[node name="${node}" type="${character ? 'CharacterBody2D' : 'StaticBody2D'}"]
y_sort_enabled = true
${character ? 'motion_mode = 1\nscript = ExtResource("2_script")\n' : ''}
[node name="AnimatedSprite2D" type="AnimatedSprite2D" parent="."]
texture_filter = 1
offset = Vector2(0, ${offY})
sprite_frames = ExtResource("1_frames")
animation = &"${first}"
autoplay = "${first}"

[node name="CollisionShape2D" type="CollisionShape2D" parent="."]
position = Vector2(0, ${-Math.max(2, Math.round(spriteSize * 0.09))})
shape = SubResource("RectangleShape2D_feet")
`;
}

/** Files of a Godot sprite folder (sheet, SpriteFrames, scene, script, JSON). */
export function spriteGodotEntries(o: { folder: string; base: string; name: string; character: boolean; enemy?: boolean; png: Uint8Array; meta: SheetMeta; feetInFrame: number; spriteSize: number }): ZipEntry[] {
  const { folder, base, meta } = o;
  const entries: ZipEntry[] = [
    { path: `${folder}/${base}.png`, data: o.png },
    { path: `${folder}/${base}.json`, data: JSON.stringify(meta, null, 1) },
    { path: `${folder}/${base}_frames.tres`, data: godotFrames(`${base}.png`, meta) },
    { path: `${folder}/${base}.tscn`, data: godotScene(o.name, o.character, meta.frameWidth, o.feetInFrame, o.spriteSize, base, meta) },
  ];
  if (o.character) entries.push({ path: `${folder}/${base}.gd`, data: o.enemy ? ENEMY_SCRIPT : PLAYER_SCRIPT });
  return entries;
}

function readme(doc: SpriteDoc, base: string, meta: SheetMeta): string {
  const list = meta.animations.map((a) => `- \`${a.name}\` – ${a.frames} Frames, ${a.fps} fps${a.loop ? ', Schleife' : ''}`).join('\n');
  return `# ${doc.name} – aus MapForge

## Godot 4 (3 Schritte)

1. Diesen Ordner \`${base}/\` in dein Godot-Projekt ziehen (egal wohin).
2. \`${base}.tscn\` in deine Szene ziehen – fertig.
3. ${doc.kind === 'character' ? 'Starten: Pfeiltasten bewegen die Figur, "walk" / "idle" (mit Richtungen) laufen automatisch.' : doc.kind === 'creature' ? 'Starten: der Gegner wartet und verfolgt die Spielfigur (Gruppe "player"), sobald sie nah ist.' : 'Das Objekt spielt seine erste Animation automatisch ab.'}

Pixel bleiben scharf (Filter "Nearest" ist gesetzt). Die Füße liegen am Ursprung des Knotens –
passt zu Y-Sort und zur MapForge-Karte.

## Andere Engines (Unity, GDevelop, Phaser …)

- \`${base}.png\` – Spritesheet, eine Zeile pro Animation, Frame-Größe ${meta.frameWidth} × ${meta.frameHeight} px
- \`${base}.json\` – Zeilen, Frame-Anzahl, fps, Schleife

## Animationen

${list}
`;
}

export function exportSpriteGodot(doc: SpriteDoc, c0: ExportChoice) {
  const base = safeFileName(doc.name) || 'sprite';
  const { canvas, meta } = sheet(doc, c0.anims, c0.fps, c0.views, c0.custom);
  const entries: ZipEntry[] = [
    ...spriteGodotEntries({ folder: base, base, name: doc.name, character: doc.kind !== 'object', enemy: doc.kind === 'creature', png: pngBytes(canvas), meta, feetInFrame: feetOf(doc), spriteSize: doc.size }),
    { path: `${base}/README.md`, data: readme(doc, base, meta) },
    { path: `${base}/${base}_still.png`, data: dataUrlToBytes(toPng(compose(doc), doc.size)) },
  ];
  downloadBlob(createZip(entries), `${base}-godot.zip`);
}

/** frames of a sheet as separate PNGs (for engines / tools that want single images) */
export function exportFramesZip(doc: SpriteDoc, c0: ExportChoice) {
  const base = safeFileName(doc.name) || 'sprite';
  const { canvas, meta } = sheet(doc, c0.anims, c0.fps, c0.views, c0.custom);
  const n = frameSize(doc.size);
  const entries: ZipEntry[] = [];
  for (const a of meta.animations)
    for (let i = 0; i < a.frames; i++) {
      const c = document.createElement('canvas');
      c.width = c.height = n;
      c.getContext('2d')!.drawImage(canvas, i * n, a.row * n, n, n, 0, 0, n, n);
      entries.push({ path: `${base}/${a.name}_${String(i).padStart(2, '0')}.png`, data: pngBytes(c) });
    }
  entries.push({ path: `${base}/${base}.json`, data: JSON.stringify(meta, null, 1) });
  downloadBlob(createZip(entries), `${base}-frames.zip`);
}
